"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { Card, CardBody, CardHeader } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Field, Input, Select } from "@/components/ui/input";
import { LayersIcon, SparklesIcon, VideoIcon } from "@/components/ui/icons";
import {
  AssemblyCapabilities,
  AssemblyResult,
  AssemblySceneInput,
  ResearchSession,
  fetchAssemblyCapabilities,
  fetchResearchSessions,
  mediaAssetUrl,
  startAssembly,
} from "@/lib/api";

/** Matches the DTO, so the form cannot submit a body the API will only reject. */
const MAX_HEADING = 200;
const MAX_BODY = 4000;
const MAX_SCENES = 40;

/**
 * On-screen time for a scene, mirroring the assembler's own estimate.
 *
 * The server measures the recipe it will really submit and refuses an over-long
 * movie, so this number is a preview rather than the authority. Duplicating the
 * arithmetic here is what lets the button explain the refusal before it happens
 * instead of after a round trip.
 */
function sceneSeconds(body: string): number {
  return Math.min(12, Math.max(4, Math.round(body.length / 14) + 2));
}

function titleCardSeconds(title: string): number {
  return Math.min(8, Math.max(3, Math.round(title.length / 18) + 2));
}

function estimateSeconds(title: string, subtitle: string, scenes: AssemblySceneInput[], outro: string): number {
  // Longest element sets the scene's length, not the sum: a voice element carries
  // duration -1 because JSON2Video sizes it from its own text, and a scene's
  // elements play together.
  let total = titleCardSeconds(title);
  if (subtitle.trim()) total += 3;
  for (const scene of scenes) total += Math.max(3, sceneSeconds(scene.body));
  if (outro.trim()) total += 4;
  return total;
}

/**
 * Turn a research answer into scenes.
 *
 * Markdown headings become scene headings, because a report that already has a
 * structure should not be re-invented. An answer with no headings is cut at its
 * blank lines instead. Citation markers are left in: the recipe is stored with the
 * asset, and a video whose text can be traced back to its sources is worth more than
 * a tidier one.
 */
function scenesFromAnswer(answer: string, fallbackHeading: string): AssemblySceneInput[] {
  const scenes: AssemblySceneInput[] = [];
  const lines = answer.split(/\r?\n/);
  let heading = fallbackHeading;
  let body: string[] = [];
  let sawHeading = false;

  const flush = () => {
    const text = body.join("\n").trim();
    if (heading.trim() || text) {
      scenes.push({ heading: (heading.trim() || fallbackHeading).slice(0, MAX_HEADING), body: text.slice(0, MAX_BODY) });
    }
    body = [];
  };

  for (const line of lines) {
    const match = line.match(/^#{1,6}\s+(.*)$/);
    if (match) {
      if (sawHeading || body.join("").trim()) flush();
      heading = match[1].trim();
      sawHeading = true;
      continue;
    }
    if (sawHeading && line.trim() === "" && body.join("").trim() === "") continue;
    body.push(line);
  }
  flush();

  if (scenes.length === 1 && scenes[0].body.trim() === "") return [];
  const usable = scenes.filter((scene) => scene.heading.trim() && scene.body.trim());
  return usable.slice(0, MAX_SCENES);
}

/**
 * Assembling a document into a video, which is not clip generation.
 *
 * It lives on its own card and calls its own route because it is a different thing:
 * there is no prompt to write and no model to pick, the render is minutes long, and
 * the button spends seconds of a grant that does not come back. It is deliberately
 * not reachable from the "Generate a clip" form, so a mistake here can never send a
 * document to be rendered as though it were an idea.
 *
 * The source is a real research answer rather than free text, so what gets rendered
 * is something the user already wrote and can check.
 */
export function AssemblyPanel({ onAssembled }: { onAssembled?: () => void }) {
  const [capabilities, setCapabilities] = useState<AssemblyCapabilities | null>(null);
  const [sessions, setSessions] = useState<ResearchSession[]>([]);
  const [selected, setSelected] = useState("");
  const [title, setTitle] = useState("");
  const [subtitle, setSubtitle] = useState("");
  const [outro, setOutro] = useState("Generated by ISOBASH");
  const [resolution, setResolution] = useState("");
  const [voiceover, setVoiceover] = useState(true);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<AssemblyResult | null>(null);

  const load = useCallback((signal?: AbortSignal) => {
    Promise.all([fetchAssemblyCapabilities(signal), fetchResearchSessions(signal)])
      .then(([caps, reports]) => {
        setCapabilities(caps);
        setSessions(reports.filter((report) => report.status === "COMPLETED" && (report.answer ?? "").trim()));
        if (caps.resolutions.length > 0) setResolution(caps.resolutions[caps.resolutions.length - 1]);
      })
      .catch((err) => {
        if ((err as Error).name === "AbortError") return;
        setError(err instanceof Error ? err.message : "Video assembly could not be read.");
      });
  }, []);

  useEffect(() => {
    const controller = new AbortController();
    load(controller.signal);
    return () => controller.abort();
  }, [load]);

  const report = useMemo(
    () => sessions.find((session) => session.id === selected) ?? null,
    [sessions, selected],
  );

  const scenes = useMemo(
    () => (report ? scenesFromAnswer(report.answer ?? "", report.question) : []),
    [report],
  );

  /**
   * Picking a report fills the form from it. Editing afterwards is allowed and the
   * selection is not overwritten, because a user trimming a title is not choosing a
   * different report.
   */
  const choose = (id: string) => {
    setSelected(id);
    setResult(null);
    setError(null);
    const picked = sessions.find((session) => session.id === id) ?? null;
    setTitle(picked ? picked.question.slice(0, MAX_HEADING) : "");
    setSubtitle(picked?.provider ? `${picked.provider} answered this, and ISOBASH is reading it aloud.` : "");
  };

  const seconds = estimateSeconds(title, subtitle, scenes, outro);
  const available = capabilities?.available === true;
  const overPlan = capabilities ? seconds > capabilities.maxSeconds : false;
  const overGrant = capabilities?.remainingReadable && capabilities.remainingSeconds !== null ? seconds > capabilities.remainingSeconds : false;
  const blocked = !available || scenes.length === 0 || overPlan || overGrant;

  const assemble = async (event: FormEvent) => {
    event.preventDefault();
    if (blocked || !report) return;
    setBusy(true);
    setError(null);
    setResult(null);
    startAssembly({
      title: title.trim() || report.question,
      ...(subtitle.trim() ? { subtitle: subtitle.trim().slice(0, 300) } : {}),
      scenes,
      voiceover,
      ...(outro.trim() ? { outro: outro.trim().slice(0, 1000) } : {}),
      resolution: resolution || (capabilities?.resolutions[0] ?? "hd"),
      source: "research",
      sourceId: report.id,
    })
      .then((value) => {
        setResult(value);
        onAssembled?.();
      })
      .catch((err) => setError(err instanceof Error ? err.message : "The video could not be assembled."))
      .finally(() => setBusy(false));
  };

  return (
    <Card>
      <CardHeader
        title="Assemble a report into a video"
        subtitle="A different thing from generating a clip: this lays out and reads a report you already have. It is rendered by JSON2Video, it takes minutes, and it spends seconds of a grant that does not refill."
        icon={<LayersIcon className="h-4 w-4" />}
      />
      <CardBody className="space-y-4">
        {!capabilities ? (
          <Skeleton className="h-32 w-full" />
        ) : !available ? (
          <p className="rounded-xl bg-warning/10 px-3 py-2.5 text-xs text-warning ring-1 ring-warning/20">
            {capabilities.detail}
          </p>
        ) : (
          <div className="flex flex-wrap items-center gap-2 text-[11px] text-muted-foreground">
            <Badge tone={capabilities.remainingReadable ? "success" : "warning"}>
              {capabilities.remainingReadable
                ? `${capabilities.remainingSeconds}s of video left`
                : "balance unknown"}
            </Badge>
            <Badge tone="neutral">max {capabilities.maxSeconds}s</Badge>
            {capabilities.watermarked ? <Badge tone="warning">watermarked</Badge> : null}
            {capabilities.nonRenewing ? <Badge tone="warning">does not renew</Badge> : null}
            {capabilities.voiceoverAvailable ? <Badge tone="accent">narration free</Badge> : null}
          </div>
        )}

        {sessions.length === 0 && capabilities ? (
          <p className="text-xs text-muted-foreground">
            No finished research report to assemble yet. Run a research session first, then come back here.
          </p>
        ) : null}

        <form onSubmit={assemble} className="space-y-4">
          <Field
            label="Report"
            htmlFor="assembly-report"
            hint="Only finished reports with an answer can be laid out. Nothing is sent to JSON2Video until you assemble one."
          >
            <Select id="assembly-report" value={selected} onChange={(event) => choose(event.target.value)} disabled={busy}>
              <option value="">Choose a research report</option>
              {sessions.map((session) => (
                <option key={session.id} value={session.id}>
                  {session.question}
                </option>
              ))}
            </Select>
          </Field>

          {report ? (
            <>
              <Field label="Title" htmlFor="assembly-title" hint={`${title.length} of ${MAX_HEADING} characters.`}>
                <Input
                  id="assembly-title"
                  value={title}
                  maxLength={MAX_HEADING}
                  onChange={(event) => setTitle(event.target.value)}
                  disabled={busy}
                />
              </Field>

              <Field label="Subtitle" htmlFor="assembly-subtitle" hint="Optional. Left empty, the video opens straight into the first scene.">
                <Input
                  id="assembly-subtitle"
                  value={subtitle}
                  maxLength={300}
                  onChange={(event) => setSubtitle(event.target.value)}
                  disabled={busy}
                />
              </Field>

              <div className="rounded-xl bg-surface-2 px-3 py-2.5 ring-1 ring-border">
                <p className="text-[13px] font-medium text-foreground">
                  {scenes.length} scene{scenes.length === 1 ? "" : "s"} from this report
                </p>
                <ul className="mt-2 space-y-1 text-[11px] text-muted-foreground">
                  {scenes.map((scene, index) => (
                    <li key={`${index}-${scene.heading}`}>
                      <span className="font-medium text-foreground">{scene.heading}</span> · {sceneSeconds(scene.body)}s
                    </li>
                  ))}
                </ul>
              </div>

              <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
                <Field label="Resolution" htmlFor="assembly-resolution">
                  <Select
                    id="assembly-resolution"
                    value={resolution}
                    onChange={(event) => setResolution(event.target.value)}
                    disabled={busy || !available}
                  >
                    {(capabilities?.resolutions ?? []).map((size) => (
                      <option key={size} value={size}>
                        {size}
                      </option>
                    ))}
                  </Select>
                </Field>

                <Field label="Narration" htmlFor="assembly-voiceover" hint="Text to speech costs 0 credits, so a narrated video costs the same.">
                  <label className="flex h-11 items-center gap-2 text-sm">
                    <input
                      id="assembly-voiceover"
                      type="checkbox"
                      checked={voiceover}
                      disabled={busy || capabilities?.voiceoverAvailable !== true}
                      onChange={(event) => setVoiceover(event.target.checked)}
                    />
                    Read the report aloud
                  </label>
                </Field>

                <Field label="Outro" htmlFor="assembly-outro" hint="Optional closing scene, e.g. a source line.">
                  <Input
                    id="assembly-outro"
                    value={outro}
                    maxLength={1000}
                    onChange={(event) => setOutro(event.target.value)}
                    disabled={busy}
                  />
                </Field>
              </div>

              <p
                className={`rounded-xl px-3 py-2.5 text-xs ring-1 ${
                  overPlan || overGrant
                    ? "bg-danger/10 text-danger ring-danger/20"
                    : "bg-surface-2 text-muted-foreground ring-border"
                }`}
              >
                About {seconds}s of video, {overPlan
                  ? `over the ${capabilities?.maxSeconds}s this plan allows for one movie.`
                  : overGrant
                    ? `more than the ${capabilities?.remainingSeconds}s left on the account.`
                    : "at 1 credit per second."}
              </p>
            </>
          ) : null}

          {error ? (
            <p className="rounded-xl bg-danger/10 px-3 py-2.5 text-xs text-danger ring-1 ring-danger/20">{error}</p>
          ) : null}

          <Button type="submit" disabled={blocked || busy} variant="accent">
            {busy ? (
              <>
                <SparklesIcon className="h-4 w-4" /> Rendering. This takes minutes.
              </>
            ) : (
              <>
                <VideoIcon className="h-4 w-4" /> Assemble the video
              </>
            )}
          </Button>
          {capabilities && !capabilities.available ? (
            <p className="text-[11px] text-muted-foreground">{capabilities.detail}</p>
          ) : null}
        </form>

        {result ? (
          <div className="space-y-2 rounded-xl bg-surface-2 px-3 py-3 ring-1 ring-border">
            <p className="text-[13px] font-medium text-foreground">
              Assembled, and stored as ISOBASH&apos;s own copy. JSON2Video project {result.projectId}.
            </p>
            <video
              src={mediaAssetUrl(result.asset.id)}
              controls
              preload="metadata"
              playsInline
              className="w-full rounded-lg bg-surface-3"
            >
              <track kind="captions" />
            </video>
            {result.asset.note ? (
              <p className="text-[11px] text-muted-foreground">{result.asset.note}</p>
            ) : null}
          </div>
        ) : null}
      </CardBody>
    </Card>
  );
}