"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
var __param = (this && this.__param) || function (paramIndex, decorator) {
    return function (target, key) { decorator(target, key, paramIndex); }
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.FilesService = void 0;
const common_1 = require("@nestjs/common");
const client_1 = require("@prisma/client");
const api_error_1 = require("../shared/errors/api-error");
const inject_config_1 = require("../shared/config/inject-config");
const prisma_service_1 = require("../prisma/prisma.service");
const storage_service_1 = require("../shared/storage/storage.service");
const embedding_service_1 = require("./embedding.service");
const file_processor_service_1 = require("./file-processor.service");
const file_kinds_1 = require("./file-kinds");
/**
 * Phase 12 files service.
 *
 * Every read is owner-scoped and answers 404 for someone else's file, never 403:
 * the existence of another user's upload is not this caller's business. The
 * absolute path of a stored file never leaves the process.
 */
let FilesService = class FilesService {
    prisma;
    storage;
    processor;
    embeddings;
    config;
    constructor(prisma, storage, processor, embeddings, config) {
        this.prisma = prisma;
        this.storage = storage;
        this.processor = processor;
        this.embeddings = embeddings;
        this.config = config;
    }
    async capabilities() {
        const embedding = await this.embeddings.availability();
        const [files, chunks, embedded] = await Promise.all([
            this.prisma.storedFile.count(),
            this.prisma.fileChunk.count(),
            this.prisma.fileChunk.count({ where: { embedding: { not: client_1.Prisma.DbNull } } }),
        ]);
        return {
            upload: {
                maxBytes: this.config.files.maxBytes,
                maxFilesPerUser: this.config.files.maxFilesPerUser,
                maxTotalBytesPerUser: this.config.files.maxTotalBytesPerUser,
                types: file_kinds_1.SUPPORTED_EXTENSIONS,
                detail: 'Files are checked for size, extension, byte signature and UTF-8 validity before anything is written. The stored path is generated by the server, never taken from the client.',
            },
            extraction: {
                text: true,
                markdown: true,
                csv: true,
                json: true,
                html: true,
                pdf: true,
                images: false,
                officeAndArchives: false,
                maxExtractedCharacters: this.config.files.maxExtractedCharacters,
                maxChunksPerFile: this.config.files.maxChunksPerFile,
                chunkSize: this.config.files.chunkSize,
                chunkOverlap: this.config.files.chunkOverlap,
                detail: 'Text, markdown, CSV, JSON, HTML and text-layer PDFs are extracted for real. Images and ZIP-based office documents are stored and downloadable but are not parsed, and say so. OCR is not available.',
            },
            embeddings: embedding,
            knowledge: {
                chunkCount: chunks,
                embeddedChunks: embedded,
                storedFiles: files,
                searchCandidateLimit: this.config.files.searchCandidateLimit,
                detail: 'Keyword search always works over stored text. Vector search runs when embeddings are available and is reported per search, never assumed.',
            },
        };
    }
    list(userId, query = {}) {
        return this.prisma.storedFile.findMany({
            where: {
                userId,
                ...(query.status ? { status: query.status } : {}),
                ...(query.kind ? { kind: query.kind } : {}),
                ...(query.projectId !== undefined ? { projectId: query.projectId } : {}),
            },
            orderBy: { createdAt: 'desc' },
            take: Math.min(Math.max(query.limit ?? 50, 1), 200),
            select: {
                id: true,
                originalName: true,
                extension: true,
                kind: true,
                mimeType: true,
                sizeBytes: true,
                status: true,
                error: true,
                warning: true,
                extractable: true,
                characters: true,
                chunkCount: true,
                truncated: true,
                embeddingModel: true,
                embeddedAt: true,
                processedAt: true,
                projectId: true,
                createdAt: true,
            },
        });
    }
    async get(userId, id) {
        return this.require(userId, id, { includeChunks: true });
    }
    /** The extracted text, capped. The full text is never shipped unprompted. */
    async text(userId, id, limit) {
        const file = await this.require(userId, id);
        const cap = Math.min(Math.max(limit ?? this.config.files.maxPreviewCharacters, 200), this.config.files.maxExtractedCharacters);
        return {
            id: file.id,
            originalName: file.originalName,
            kind: file.kind,
            status: file.status,
            characters: file.characters,
            truncated: file.truncated || cap < file.characters,
            warning: file.warning,
            error: file.error,
            text: file.extractedText.slice(0, cap),
            chunkCount: file.chunkCount,
        };
    }
    async download(userId, id) {
        const file = await this.require(userId, id);
        const bytes = await this.storage.read('upload', file.relativePath);
        return { file: { name: file.originalName, bytes, mimeType: file.mimeType } };
    }
    async remove(userId, id) {
        const file = await this.require(userId, id);
        await this.prisma.storedFile.delete({ where: { id: file.id } });
        // The row is the source of truth; a leftover blob must not keep the space.
        await this.storage.remove('upload', file.relativePath);
    }
    /** Re-index a stored file, optionally attaching it to a project. */
    async reindex(userId, id, projectId) {
        const file = await this.require(userId, id);
        if (projectId !== undefined) {
            if (projectId === null) {
                await this.prisma.storedFile.update({ where: { id: file.id }, data: { projectId: null } });
            }
            else {
                const owned = await this.prisma.project.findFirst({ where: { id: projectId, ownerId: userId }, select: { id: true } });
                if (!owned) {
                    throw new api_error_1.ApiError('Project not found.', 400, 'VALIDATION_FAILED');
                }
                await this.prisma.storedFile.update({ where: { id: file.id }, data: { projectId } });
            }
        }
        await this.processor.reprocess(userId, file);
        return this.prisma.storedFile.findUnique({ where: { id: file.id } });
    }
    async accept(userId, input) {
        if (input.projectId !== null) {
            const owned = await this.prisma.project.findFirst({ where: { id: input.projectId, ownerId: userId }, select: { id: true } });
            if (!owned) {
                throw new api_error_1.ApiError('Project not found.', 400, 'VALIDATION_FAILED');
            }
        }
        if ((0, file_kinds_1.extensionOf)(input.originalName).length === 0) {
            throw new api_error_1.ApiError('The upload has no file extension, so its type cannot be verified.', 415, 'UNSUPPORTED_MEDIA_TYPE');
        }
        return this.processor.accept(userId, input);
    }
    async require(userId, id, options = {}) {
        const file = await this.prisma.storedFile.findFirst({
            where: { id, userId },
            ...(options.includeChunks
                ? { include: { chunks: { orderBy: { ordinal: 'asc' }, select: { ordinal: true, characters: true, tokenEstimate: true, embeddingModel: true, embeddedAt: true } } } }
                : {}),
        });
        if (!file) {
            throw new common_1.NotFoundException('File not found.');
        }
        return file;
    }
};
exports.FilesService = FilesService;
exports.FilesService = FilesService = __decorate([
    (0, common_1.Injectable)(),
    __param(4, (0, inject_config_1.InjectConfig)()),
    __metadata("design:paramtypes", [prisma_service_1.PrismaService,
        storage_service_1.StorageService,
        file_processor_service_1.FileProcessorService,
        embedding_service_1.EmbeddingService, Object])
], FilesService);
//# sourceMappingURL=files.service.js.map