import { Injectable, NotFoundException } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { ApiError } from '../shared/errors/api-error';
import { InjectConfig } from '../shared/config/inject-config';
import { AppConfig } from '../shared/config/configuration';
import { PrismaService } from '../prisma/prisma.service';
import { StorageService } from '../shared/storage/storage.service';
import { EmbeddingService } from './embedding.service';
import { FileProcessorService } from './file-processor.service';
import { SUPPORTED_EXTENSIONS, extensionOf } from './file-kinds';

export type FileListQuery = {
  status?: string;
  kind?: string;
  projectId?: number;
  limit?: number;
};

/**
 * Phase 12 files service.
 *
 * Every read is owner-scoped and answers 404 for someone else's file, never 403:
 * the existence of another user's upload is not this caller's business. The
 * absolute path of a stored file never leaves the process.
 */
@Injectable()
export class FilesService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly storage: StorageService,
    private readonly processor: FileProcessorService,
    private readonly embeddings: EmbeddingService,
    @InjectConfig() private readonly config: AppConfig,
  ) {}

  async capabilities() {
    const embedding = await this.embeddings.availability();
    const [files, chunks, embedded] = await Promise.all([
      this.prisma.storedFile.count(),
      this.prisma.fileChunk.count(),
      this.prisma.fileChunk.count({ where: { embedding: { not: Prisma.DbNull } } }),
    ]);
    return {
      upload: {
        maxBytes: this.config.files.maxBytes,
        maxFilesPerUser: this.config.files.maxFilesPerUser,
        maxTotalBytesPerUser: this.config.files.maxTotalBytesPerUser,
        types: SUPPORTED_EXTENSIONS,
        detail:
          'Files are checked for size, extension, byte signature and UTF-8 validity before anything is written. The stored path is generated by the server, never taken from the client.',
      },
      extraction: {
        text: true,
        markdown: true,
        csv: true,
        json: true,
        html: true,
        pdf: true,
        images: false,
        officeAndArchives: false,
        maxExtractedCharacters: this.config.files.maxExtractedCharacters,
        maxChunksPerFile: this.config.files.maxChunksPerFile,
        chunkSize: this.config.files.chunkSize,
        chunkOverlap: this.config.files.chunkOverlap,
        detail:
          'Text, markdown, CSV, JSON, HTML and text-layer PDFs are extracted for real. Images and ZIP-based office documents are stored and downloadable but are not parsed, and say so. OCR is not available.',
      },
      embeddings: embedding,
      knowledge: {
        chunkCount: chunks,
        embeddedChunks: embedded,
        storedFiles: files,
        searchCandidateLimit: this.config.files.searchCandidateLimit,
        detail:
          'Keyword search always works over stored text. Vector search runs when embeddings are available and is reported per search, never assumed.',
      },
    };
  }

  list(userId: number, query: FileListQuery = {}) {
    return this.prisma.storedFile.findMany({
      where: {
        userId,
        ...(query.status ? { status: query.status as never } : {}),
        ...(query.kind ? { kind: query.kind } : {}),
        ...(query.projectId !== undefined ? { projectId: query.projectId } : {}),
      },
      orderBy: { createdAt: 'desc' },
      take: Math.min(Math.max(query.limit ?? 50, 1), 200),
      select: {
        id: true,
        originalName: true,
        extension: true,
        kind: true,
        mimeType: true,
        sizeBytes: true,
        status: true,
        error: true,
        warning: true,
        extractable: true,
        characters: true,
        chunkCount: true,
        truncated: true,
        embeddingModel: true,
        embeddedAt: true,
        processedAt: true,
        projectId: true,
        createdAt: true,
      },
    });
  }

  async get(userId: number, id: string) {
    return this.require(userId, id, { includeChunks: true });
  }

  /** The extracted text, capped. The full text is never shipped unprompted. */
  async text(userId: number, id: string, limit?: number) {
    const file = await this.require(userId, id);
    const cap = Math.min(Math.max(limit ?? this.config.files.maxPreviewCharacters, 200), this.config.files.maxExtractedCharacters);
    return {
      id: file.id,
      originalName: file.originalName,
      kind: file.kind,
      status: file.status,
      characters: file.characters,
      truncated: file.truncated || cap < file.characters,
      warning: file.warning,
      error: file.error,
      text: file.extractedText.slice(0, cap),
      chunkCount: file.chunkCount,
    };
  }

  async download(userId: number, id: string): Promise<{ file: { name: string; bytes: Buffer; mimeType: string } }> {
    const file = await this.require(userId, id);
    const bytes = await this.storage.read('upload', file.relativePath);
    return { file: { name: file.originalName, bytes, mimeType: file.mimeType } };
  }

  async remove(userId: number, id: string) {
    const file = await this.require(userId, id);
    await this.prisma.storedFile.delete({ where: { id: file.id } });
    // The row is the source of truth; a leftover blob must not keep the space.
    await this.storage.remove('upload', file.relativePath);
  }

  /** Re-index a stored file, optionally attaching it to a project. */
  async reindex(userId: number, id: string, projectId?: number | null) {
    const file = await this.require(userId, id);
    if (projectId !== undefined) {
      if (projectId === null) {
        await this.prisma.storedFile.update({ where: { id: file.id }, data: { projectId: null } });
      } else {
        const owned = await this.prisma.project.findFirst({ where: { id: projectId, ownerId: userId }, select: { id: true } });
        if (!owned) {
          throw new ApiError('Project not found.', 400, 'VALIDATION_FAILED');
        }
        await this.prisma.storedFile.update({ where: { id: file.id }, data: { projectId } });
      }
    }
    await this.processor.reprocess(userId, file);
    return this.prisma.storedFile.findUnique({ where: { id: file.id } });
  }

  async accept(
    userId: number,
    input: { originalName: string; declaredMimeType: string; bytes: Buffer; projectId: number | null },
  ) {
    if (input.projectId !== null) {
      const owned = await this.prisma.project.findFirst({ where: { id: input.projectId, ownerId: userId }, select: { id: true } });
      if (!owned) {
        throw new ApiError('Project not found.', 400, 'VALIDATION_FAILED');
      }
    }
    if (extensionOf(input.originalName).length === 0) {
      throw new ApiError('The upload has no file extension, so its type cannot be verified.', 415, 'UNSUPPORTED_MEDIA_TYPE');
    }
    return this.processor.accept(userId, input);
  }

  private async require(userId: number, id: string, options: { includeChunks?: boolean } = {}) {
    const file = await this.prisma.storedFile.findFirst({
      where: { id, userId },
      ...(options.includeChunks
        ? { include: { chunks: { orderBy: { ordinal: 'asc' }, select: { ordinal: true, characters: true, tokenEstimate: true, embeddingModel: true, embeddedAt: true } } } }
        : {}),
    });
    if (!file) {
      throw new NotFoundException('File not found.');
    }
    return file;
  }
}
